ucgmsim/visualisation

im_plotting/im_plot.py
updated help mesaage
csv_filepath          path to input metadata file
to 
csv_filepath          path to input csv file
=> updated -h help message

comparisons/waveforms_sim_obs.py
added n_stations (random), allowed plotting of just obs or sim, some tidy up
https://quakecore.atlassian.net/browse/QSW-632
=> Support for n_stations and only sim or obs data

gmt/plot_srf_map.py
xrange to range for running plot_srf in slurm_gm_workflow
=> python2to3 xrange to range

visualization/comparisons/waveforms_sim_sim.py
Takes in two BB.bin files and generates comparison wavefrom images for all shared stations
=> Added BB.bin comparison waveform plotting script

visualization/comparisons/im_rrup_mean.py
Corrected im_names debug value.
=> Fixed error bar plotting.

setup.py
that specific script is no longer there. removing it from setup.py
=> remove a line from setup.py since it no longer there

visualization/gmt/plot_items.py
continuous prevents discretising colour changes if input cpt is continuous too
continuing means out of cpt range is same as max/min range
can specify contour increment or use cpt increments
can use input cpt as is, which is the default for categorical
=> cpt options

visualization/comparisons/im_rrup.py, visualization/comparisons/im_rrup_mean.py, visualization/comparisons/spatial_im_rrup_epsilon_plot.py, visualization/comparisons/waveforms_sim_sim.py, visualization/gmt/plot_srf_map.py, visualization/gmt/plot_ts.py
=> 2 xyts plotting

visualization/gmt/plot_srf_map.py
=> improve depth plot

visualization/comparisons/psa_ratios.py, visualization/gmt/plot_srf_map.py
Without this there are issues with string vs byte string loading
=> python3 update

compare/compare_runs.py, im/im_ratios.py, im/im_rrup_mean.py, im/psa_bias.py, im/psa_comparisons.py, im/psa_ratios_rrup.py, im/spatialise_im.py, sources/plot_items.py, visualization/plot_items_wrapper.py
Based on https://wiki.canterbury.ac.nz/display/QuakeCore/Ideas%20for%20improvement%20to%20Visualisation
=> Orchestrate various plotting to compare two runs

Jenkinsfile
Tests passed ok and storage footprint is under control
=> Creating virt env

Jenkinsfile
Discovered a way to define a variable
=> Updated Jenkinsfile with new environment directive

cybershake/README.md, cybershake/scenario_epsilon.py, cybershake/scenario_epsilon_config.yaml, cybershake/scenario_im_fault.py, cybershake/scenario_im_fault_config.yaml, cybershake/scenario_ratios.py, cybershake/scenario_ratios_config.yaml
Some adjustments needed to be made due to summarise_all_rel_im changes.
Now a component in the config to select from the im csv
Bug Fix - Using subprocess.call instead of subprocess.Popen due to Popen not waiting until complete to continue script. (Cause problems as some files were still generating and were being passed into plot items)
=> Scenario Plotting adjustments

README.md
Migrating status sticker to the new host too.
=> Migrating Jenkins from EC2 to 1P 

im/im_rrup_mean.py, prototype/plot_proximity.py, prototype/spatial_im_rrup_epsilon_plot.py, sources/plot_srf_map.py, sources/plot_srf_slip_rise_rake.py
before:
After:
Though there may be issues with the depth finding function? It looks like it should work though as it's finding the max across all the points?
Maybe just needs some rounding up on the CPT max?
=> cpt changes

sources/plot_items.py
Just because plot_items needed more customisation.
=> added option to disable roads/highways on the map plots

compare/compare_runs.py, sources/plot_srf_map.py
Any regions added in future will automatically show up here, and any regions in regions.ll but not in the region dict will alert the user with an exception
Draft pending https://github.com/ucgmsim/qcore/pull/285
=> Replace region corners loading with region_dict.

sources/gsf_plot.py
Adds a utility to plot a GSF file. Useful for debugging output of utilities like `fault_seg2gsf` or the new python gsf generator.
=> Gsf plotting

visualization/plot_items_wrapper.py
Uses pathlib to achieve the same thing. Required to merge ucgmsim/qcore#309.
=> remove change_file_ext
